### ISSUE TITLE
imeplement poetry installation 

### ISSUE THREAD

**Issue by gregordecristoforo** [uit-cosmo/fpp-analysis-tools#1]
Installing this package with poetry didn't work for me since poetry wasn't able to identify the package `PyWavelets`. Have you ever seen such a problem @engeir? It would be good to standardize the installation process across all packages in uit-cosmo.

**Comment by engeir** [comment]
Hmm, I was actually able to install and import it using poetry (tried `poetry add pywavelets` in a new project as well, and importing `pywt` worked):

```console
$ poetry search pywavelets | grep PyWavelets
 PyWavelets, wavelet transform module
 Process MIT-BIH Arrhythmia Database records with PyWavelets
```

I made a pull request you can have a look at, I might have used wrong names for the package etc. (Also, I _think_ poetry might be a bit picky about package name and module name being different: `fpp-analysis-tools` vs. `analysistools`.)

**Comment by gregordecristoforo** [comment]
That works, thanks! I'll upload the package with poetry (version 0.1.1) and remove the old setup file
