### ISSUE TITLE
Setting pdf_plot=True in estimate_delays() doesn't show the inset 

### ISSUE THREAD

**Issue by sajidah-ahmed** [uit-cosmo/fpp-analysis-tools#19]
I declare the axes and I set `plot_pdf = True`:

```
fig, axes = plt.subplots()
average_time_delay, parameters = fa.estimate_delays(x=data_1, y=data_2, dt=sampling_time, distribution=invgamma, ax=axes, plot_pdf=True)
plt.legend()
plt.show()
```
The inset isn't showing still. Is something missing?

**Comment by Sosnowsky** [comment]
Hm, I use the same code in the same way that you do and I do get the inset plot. I believe you used to get it also before, I haven't changed this functionality. 
Can you provide a working example where the pdf is not shown?

**Comment by Sosnowsky** [comment]
The code that you provide works seems to work fine (If I change data_1 and data_2 to synthetic data arrays, I get the expected behaviour)

**Comment by sajidah-ahmed** [comment]
Hi Juan, did you have pre-defined LateX commands somewhere? I tried to re-plot this on python as opposed to Jupyter and it finally spat out an error. I think I know why the inset doesn't show up, but everything else does.

```
ValueError: 
\wh{R_{\tilde{\Phi}, \tilde{\Psi}}}(r)
^
Unknown symbol: \wh, found '\'  (at char 0), (line:1, col:1)
```

Is `\wh` meant to be `\widehat` ? If so, it's not recognised.

**Comment by sajidah-ahmed** [comment]
> Hm, I use the same code in the same way that you do and I do get the inset plot. I believe you used to get it also before, I haven't changed this functionality. Can you provide a working example where the pdf is not shown?

This is what it looks like with the code snippet I showed earlier:
![image](https://user-images.githubusercontent.com/58845635/203150969-69f691d7-6832-43c8-a90f-a5509b7647dd.png)

**Comment by Sosnowsky** [comment]
Of course, I didn't think about this. This should fix it: https://github.com/uit-cosmo/fpp-analysis-tools/pull/20

**Comment by sajidah-ahmed** [comment]
You also need to change it in plot_optimization(). Thanks!

**Comment by sajidah-ahmed** [comment]
All good! I guess it would be a good idea to have the location of the inset as an input parameter. Currently, it'll plot on the bottom-right corner. This can be raised in a separate issue.

![image](https://user-images.githubusercontent.com/58845635/203254345-d587dd58-05a4-4dfd-afef-cdd84042916f.png)
